-- public.company definition

-- Drop table

-- DROP TABLE public.company;

CREATE TABLE public.company (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamptz NOT NULL DEFAULT now(),
	company_name text NULL DEFAULT ''::text,
	mobile text NULL DEFAULT ''::text,
	CONSTRAINT company_pkey PRIMARY KEY (id)
);

INSERT INTO public.company (created_at,company_name,mobile) VALUES
	 ('2024-02-14 04:17:24.859997+00','Company1','123-456-7890'),
	 ('2024-02-17 05:00:00+00','Company2','800-COMPANY2');

-- public.form_schema definition

-- Drop table

-- DROP TABLE public.form_schema;

CREATE TABLE public.form_schema (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamptz NOT NULL DEFAULT now(),
	form_name text NULL,
	"schema" json NULL,
	ui_schema json NULL,
	CONSTRAINT "formSchema_pkey" PRIMARY KEY (id)
);

INSERT INTO public.form_schema (created_at,form_name,"schema",ui_schema) VALUES
	 ('2024-02-18 02:39:41.461032+00','partner','{"type":"object","title":"partner Details","required":["name","phone","address","city","state","zip","country"],"properties":{"zip":{"type":"string","title":"Zip","default":"default zip","maxLength":50,"minLength":1},"city":{"type":"string","title":"City","default":"default city","maxLength":50,"minLength":1},"name":{"type":"string","title":"Name","default":"default name","maxLength":50,"minLength":1},"phone":{"type":"string","title":"Phone","default":"default phone","maxLength":50,"minLength":1},"state":{"type":"string","title":"State","default":"default state","maxLength":50,"minLength":1},"address":{"type":"string","title":"Address","default":"default address","maxLength":50,"minLength":1},"country":{"type":"string","title":"Country","default":"default country","maxLength":50,"minLength":1}},"description":"Enter partner Data"}','{"ui:order":["name","phone","address","city","state","zip","country"]}'),
	 ('2024-02-18 17:08:22.238317+00','nurse','{"type":"object","title":"Nurse Details","required":["name","phone","address","city","state","zip","country"],"properties":{"zip":{"type":"string","title":"Zip","default":"default zip","maxLength":50,"minLength":1},"city":{"type":"string","title":"City","default":"default city","maxLength":50,"minLength":1},"name":{"type":"string","title":"Name","default":"default name","maxLength":50,"minLength":1},"phone":{"type":"string","title":"Phone","default":"default phone","maxLength":50,"minLength":1},"state":{"type":"string","title":"State","default":"default state","maxLength":50,"minLength":1},"address":{"type":"string","title":"Address","default":"default address","maxLength":50,"minLength":1},"country":{"type":"string","title":"Country","default":"default country","maxLength":50,"minLength":1}},"description":"Enter partner Data"}','{"ui:order":["phone","name","address","city","state","zip","country"]}');

-- public.partner definition

-- Drop table

-- DROP TABLE public.partner;

CREATE TABLE public.partner (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamptz NOT NULL DEFAULT now(),
	"name" text NULL,
	phone text NULL,
	address text NULL,
	city text NULL,
	state text NULL,
	zip text NULL,
	country text NULL,
	CONSTRAINT partner_pkey PRIMARY KEY (id)
);

INSERT INTO public.partner (created_at,"name",phone,address,city,state,zip,country) VALUES
	 ('2024-02-18 02:31:54.252051+00','PARTNER NAME','800-PARTNER1','123 Main Street','Anytown1','FL','12347','United States'),
	 ('2024-02-18 05:00:00+00','PARTNER2','800-PARTNER2','123 MAIN ST','ANYTOWN2','FL','123467','USA');
